### ISSUE TITLE
*Question* - How can I apply the HeaderCustomization to an Alfresco AIO sdk? 

### ISSUE THREAD

**Issue by Artemas-Muzanenhamo** [draperd/Alfresco-Share-Extensions#4]
@draperd 

I've been trying to apply this example into my Alfresco all-in-one sdk and it's proving to be challenging for me. Would you be kind enough to ellaborate on how I can apply it to the project. I tried adding the `HeaderCustomization.jar` in my `pom.xml` file of my `Alfresco-AIO sdk` within the `<shareModules>` and also in the `<dependency>` section but I have no luck as it is not being loaded. I will attach my pom.xml snap of where I've applied the jar in my `Alfresco-AIO sdk`. Since the module didn't have an `artifact-id` and `group-id` I have just named the jar as `alfresco-example-0.0.1.jar` with the `group-id` as `com.artemas.example`.

*shareModules* 👇 
<img width="530" alt="customization-in-share-modules" src="https://user-images.githubusercontent.com/29547780/39621731-a4d48ad6-4f87-11e8-86e7-f7a4746fb1db.png">

*dependencies* 👇 
<img width="540" alt="module-in-dependencies" src="https://user-images.githubusercontent.com/29547780/39621849-0ffea74c-4f88-11e8-8300-0b70d228de35.png">

**Comment by douglascrp** [comment]
That is not how Maven works.
In order to have the jar included as a dependency, you have to use Maven to package the project for you, and "install" it in your local repository.
Simply renaming the file won't make it maven-compatible.
The problem with this is that the project is not maven based, so, if you want to use it inside of an AIO project, you have to options:

1. Convert the HeaderCustomization project into a maven project (and execute what I told you before)
2. Include the HeaderCustomization project's customizations inside of your AIO project (as you seems to be new to the Maven world, I guess this would be the easier for you)

For the second option, get the folders and files from https://github.com/draperd/Alfresco-Share-Extensions/tree/master/HeaderCustomization/alfresco
and put them inside your project, using the existing folders, created for you by the sdk archetype

**Comment by Artemas-Muzanenhamo** [comment]
@douglascrp 
Lol ok, I am not new to Maven 😏 lol. I did perform step 1 of which I created my own custom `group-id` and `artifact-id` using:
```
mvn install:install-file 
  -Dfile=<path-to-file> 
  -DgroupId=<group-id> 
  -DartifactId=<artifact-id> 
  -Dversion=<version> 
  -Dpackaging=<packaging> 
  -DgeneratePom=true
```

I had been trying out a lot of theories hence I added a dependency in the `<dependencies>` tag but that was not necessary. Thanks I think I'll try the two options thanks 👍
